### ISSUE TITLE
Migration Failed on employee_disciplinaryaction

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [horilla-opensource/horilla#195]
I did a latest pull and tried to migrate, the employee_disciplinaryaction is failing.
I tried commenting the model disciplinaryaction to recreate, but there also its saying the relation already exist. 

```
  Applying employee.0002_disciplinaryaction...Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateTable: relation "employee_disciplinaryaction" already exists
````
```
root@ip-10-10-28-15:/opt/horilla# python3 manage.py makemigrations
Migrations for 'horilla_audit':
  horilla_audit/migrations/0001_initial.py
    - Create model AuditTag
    - Create model HistoryTrackingFields
    - Create model AccountBlockUnblock
Migrations for 'asset':
  asset/migrations/0001_initial.py
    - Create model Asset
    - Create model AssetAssignment
    - Create model AssetCategory
    - Create model AssetDocuments
    - Create model AssetLot
    - Create model AssetReport
    - Create model ReturnImages
    - Create model AssetRequest
  asset/migrations/0002_initial.py
    - Add field requested_employee_id to assetrequest
    - Add field asset_id to assetreport
    - Add field created_by to assetreport
    - Add field modified_by to assetreport
    - Add field company_id to assetlot
    - Add field created_by to assetlot
    - Add field modified_by to assetlot
    - Add field asset_report to assetdocuments
    - Add field created_by to assetdocuments
    - Add field modified_by to assetdocuments
    - Add field company_id to assetcategory
    - Add field created_by to assetcategory
    - Add field modified_by to assetcategory
    - Add field asset_id to assetassignment
    - Add field assign_images to assetassignment
    - Add field assigned_by_employee_id to assetassignment
    - Add field assigned_to_employee_id to assetassignment
    - Add field created_by to assetassignment
    - Add field modified_by to assetassignment
    - Add field return_images to assetassignment
    - Add field asset_category_id to asset
    - Add field asset_lot_number_id to asset
    - Add field created_by to asset
    - Add field modified_by to asset
    - Add field owner to asset
Migrations for 'attendance':
  attendance/migrations/0001_initial.py
    - Create model Attendance
    - Create model AttendanceActivity
    - Create model AttendanceGeneralSetting
    - Create model AttendanceLateComeEarlyOut
    - Create model AttendanceOverTime
    - Create model AttendanceRequestComment
    - Create model AttendanceRequestFile
    - Create model AttendanceValidationCondition
    - Create model GraceTime
    - Create model HistoricalAttendance
    - Create model PenaltyAccount
  attendance/migrations/0002_initial.py
    - Add field employee_id to penaltyaccount
    - Add field late_early_id to penaltyaccount
    - Add field leave_request_id to penaltyaccount
    - Add field leave_type_id to penaltyaccount
    - Add field modified_by to penaltyaccount
    - Add field attendance_day to historicalattendance
    - Add field created_by to historicalattendance
    - Add field employee_id to historicalattendance
    - Add field history_relation to historicalattendance
    - Add field history_tags to historicalattendance
    - Add field history_user to historicalattendance
    - Add field modified_by to historicalattendance
    - Add field shift_id to historicalattendance
    - Add field work_type_id to historicalattendance
    - Add field company_id to gracetime
    - Add field created_by to gracetime
    - Add field modified_by to gracetime
    - Add field company_id to attendancevalidationcondition
    - Add field created_by to attendancevalidationcondition
    - Add field modified_by to attendancevalidationcondition
    - Add field created_by to attendancerequestfile
    - Add field modified_by to attendancerequestfile
    - Add field created_by to attendancerequestcomment
    - Add field employee_id to attendancerequestcomment
    - Add field files to attendancerequestcomment
    - Add field modified_by to attendancerequestcomment
    - Add field request_id to attendancerequestcomment
    - Add field created_by to attendanceovertime
    - Add field employee_id to attendanceovertime
    - Add field modified_by to attendanceovertime
    - Add field attendance_id to attendancelatecomeearlyout
    - Add field created_by to attendancelatecomeearlyout
    - Add field employee_id to attendancelatecomeearlyout
    - Add field modified_by to attendancelatecomeearlyout
    - Add field company_id to attendancegeneralsetting
    - Add field created_by to attendancegeneralsetting
    - Add field modified_by to attendancegeneralsetting
    - Add field created_by to attendanceactivity
    - Add field employee_id to attendanceactivity
    - Add field modified_by to attendanceactivity
    - Add field shift_day to attendanceactivity
    - Add field attendance_day to attendance
    - Add field created_by to attendance
    - Add field employee_id to attendance
    - Add field modified_by to attendance
    - Add field shift_id to attendance
    - Add field work_type_id to attendance
    - Alter unique_together for attendanceovertime (1 constraint(s))
    - Alter unique_together for attendancelatecomeearlyout (1 constraint(s))
    - Alter unique_together for attendance (1 constraint(s))
Migrations for 'base':
  base/migrations/0001_initial.py
    - Create model Announcement
    - Create model AnnouncementComment
    - Create model AnnouncementExpire
    - Create model AnnouncementView
    - Create model Attachment
    - Create model BaserequestFile
    - Create model BiometricAttendance
    - Create model Company
    - Create model DashboardEmployeeCharts
    - Create model Department
    - Create model DriverViewed
    - Create model DynamicEmailConfiguration
    - Create model DynamicPagination
    - Create model EmailLog
    - Create model EmployeeShift
    - Create model EmployeeShiftDay
    - Create model EmployeeShiftSchedule
    - Create model EmployeeType
    - Create model HistoricalRotatingShiftAssign
    - Create model HistoricalRotatingWorkTypeAssign
    - Create model HistoricalShiftRequest
    - Create model HistoricalWorkTypeRequest
    - Create model JobPosition
    - Create model JobRole
    - Create model MultipleApprovalCondition
    - Create model MultipleApprovalManagers
    - Create model RotatingShift
    - Create model RotatingShiftAssign
    - Create model RotatingWorkType
    - Create model RotatingWorkTypeAssign
    - Create model ShiftRequest
    - Create model ShiftRequestComment
    - Create model Tags
    - Create model WorkType
    - Create model WorkTypeRequest
    - Create model WorkTypeRequestComment
  base/migrations/0002_initial.py
    - Add field employee_id to worktyperequestcomment
    - Add field files to worktyperequestcomment
    - Add field modified_by to worktyperequestcomment
    - Add field request_id to worktyperequestcomment
    - Add field created_by to worktyperequest
    - Add field employee_id to worktyperequest
    - Add field modified_by to worktyperequest
    - Add field previous_work_type_id to worktyperequest
    - Add field work_type_id to worktyperequest
    - Add field company_id to worktype
    - Add field created_by to worktype
    - Add field modified_by to worktype
    - Add field company_id to tags
    - Add field created_by to tags
    - Add field modified_by to tags
    - Add field created_by to shiftrequestcomment
    - Add field employee_id to shiftrequestcomment
    - Add field files to shiftrequestcomment
    - Add field modified_by to shiftrequestcomment
    - Add field request_id to shiftrequestcomment
    - Add field created_by to shiftrequest
    - Add field employee_id to shiftrequest
    - Add field modified_by to shiftrequest
    - Add field previous_shift_id to shiftrequest
    - Add field reallocate_to to shiftrequest
    - Add field shift_id to shiftrequest
    - Add field created_by to rotatingworktypeassign
    - Add field current_work_type to rotatingworktypeassign
    - Add field employee_id to rotatingworktypeassign
    - Add field modified_by to rotatingworktypeassign
    - Add field next_work_type to rotatingworktypeassign
    - Add field rotating_work_type_id to rotatingworktypeassign
    - Add field created_by to rotatingworktype
    - Add field employee_id to rotatingworktype
    - Add field modified_by to rotatingworktype
    - Add field work_type1 to rotatingworktype
    - Add field work_type2 to rotatingworktype
    - Add field created_by to rotatingshiftassign
    - Add field current_shift to rotatingshiftassign
    - Add field employee_id to rotatingshiftassign
    - Add field modified_by to rotatingshiftassign
    - Add field next_shift to rotatingshiftassign
    - Add field rotating_shift_id to rotatingshiftassign
    - Add field created_by to rotatingshift
    - Add field employee_id to rotatingshift
    - Add field modified_by to rotatingshift
    - Add field shift1 to rotatingshift
    - Add field shift2 to rotatingshift
    - Add field condition_id to multipleapprovalmanagers
    - Add field created_by to multipleapprovalcondition
    - Add field department to multipleapprovalcondition
    - Add field modified_by to multipleapprovalcondition
    - Add field company_id to jobrole
    - Add field created_by to jobrole
    - Add field job_position_id to jobrole
    - Add field modified_by to jobrole
    - Add field company_id to jobposition
    - Add field created_by to jobposition
    - Add field department_id to jobposition
    - Add field modified_by to jobposition
    - Add field created_by to historicalworktyperequest
    - Add field employee_id to historicalworktyperequest
    - Add field history_relation to historicalworktyperequest
    - Add field history_tags to historicalworktyperequest
    - Add field history_user to historicalworktyperequest
    - Add field modified_by to historicalworktyperequest
    - Add field previous_work_type_id to historicalworktyperequest
    - Add field work_type_id to historicalworktyperequest
    - Add field created_by to historicalshiftrequest
    - Add field employee_id to historicalshiftrequest
    - Add field history_relation to historicalshiftrequest
    - Add field history_tags to historicalshiftrequest
    - Add field history_user to historicalshiftrequest
    - Add field modified_by to historicalshiftrequest
    - Add field previous_shift_id to historicalshiftrequest
    - Add field reallocate_to to historicalshiftrequest
    - Add field shift_id to historicalshiftrequest
    - Add field created_by to historicalrotatingworktypeassign
    - Add field current_work_type to historicalrotatingworktypeassign
    - Add field employee_id to historicalrotatingworktypeassign
    - Add field history_relation to historicalrotatingworktypeassign
    - Add field history_tags to historicalrotatingworktypeassign
    - Add field history_user to historicalrotatingworktypeassign
    - Add field modified_by to historicalrotatingworktypeassign
    - Add field next_work_type to historicalrotatingworktypeassign
    - Add field rotating_work_type_id to historicalrotatingworktypeassign
    - Add field created_by to historicalrotatingshiftassign
    - Add field current_shift to historicalrotatingshiftassign
    - Add field employee_id to historicalrotatingshiftassign
    - Add field history_relation to historicalrotatingshiftassign
    - Add field history_tags to historicalrotatingshiftassign
    - Add field history_user to historicalrotatingshiftassign
    - Add field modified_by to historicalrotatingshiftassign
    - Add field next_shift to historicalrotatingshiftassign
    - Add field rotating_shift_id to historicalrotatingshiftassign
    - Add field company_id to employeetype
    - Add field created_by to employeetype
    - Add field modified_by to employeetype
    - Add field company_id to employeeshiftschedule
    - Add field created_by to employeeshiftschedule
    - Add field day to employeeshiftschedule
    - Add field modified_by to employeeshiftschedule
    - Add field shift_id to employeeshiftschedule
    - Add field company_id to employeeshiftday
    - Add field company_id to employeeshift
    - Add field created_by to employeeshift
    - Add field days to employeeshift
    - Add field grace_time_id to employeeshift
    - Add field modified_by to employeeshift
    - Add field company_id to emaillog
    - Add field user_id to dynamicpagination
    - Add field company_id to dynamicemailconfiguration
    - Add field created_by to dynamicemailconfiguration
    - Add field modified_by to dynamicemailconfiguration
    - Add field user to driverviewed
    - Add field company_id to department
    - Add field created_by to department
    - Add field modified_by to department
    - Add field created_by to dashboardemployeecharts
    - Add field employee to dashboardemployeecharts
    - Add field modified_by to dashboardemployeecharts
    - Add field created_by to company
    - Add field modified_by to company
    - Add field company_id to biometricattendance
    - Add field announcement to announcementview
    - Add field user to announcementview
    - Add field announcement_id to announcementcomment
    - Add field created_by to announcementcomment
    - Add field employee_id to announcementcomment
    - Add field modified_by to announcementcomment
    - Add field attachments to announcement
    - Add field created_by to announcement
    - Add field department to announcement
    - Add field employees to announcement
    - Add field job_position to announcement
    - Add field modified_by to announcement
    - Alter unique_together for jobrole (1 constraint(s))
    - Alter unique_together for employeeshiftschedule (1 constraint(s))
    - Alter unique_together for company (1 constraint(s))
Migrations for 'employee':
  employee/migrations/0001_initial.py
    - Create model Actiontype
    - Create model BonusPoint
    - Create model Employee
    - Create model EmployeeTag
    - Create model EmployeeWorkInformation
    - Create model PolicyMultipleFile
    - Create model Policy
    - Create model NoteFiles
    - Create model HistoricalEmployeeWorkInformation
    - Create model HistoricalBonusPoint
    - Create model EmployeeNote
    - Create model EmployeeGeneralSetting
    - Create model EmployeeBankDetails
    - Create model DisciplinaryAction
    - Add field employee_id to bonuspoint
    - Add field modified_by to bonuspoint
    - Create constraint unique_badge_id on model employee
    - Alter unique_together for employee (1 constraint(s))
Migrations for 'helpdesk':
  helpdesk/migrations/0001_initial.py
    - Create model TicketType
    - Create model Ticket
    - Create model HistoricalTicket
    - Create model FAQCategory
    - Create model FAQ
    - Create model DepartmentManager
    - Create model Comment
    - Create model Attachment
Migrations for 'horilla_documents':
  horilla_documents/migrations/0001_initial.py
    - Create model DocumentRequest
    - Create model Document
Migrations for 'leave':
  leave/migrations/0001_initial.py
    - Create model AvailableLeave
    - Create model CompensatoryLeaveRequest
    - Create model LeaveAllocationRequest
    - Create model LeaveRequest
    - Create model LeaverequestFile
    - Create model RestrictLeave
    - Create model LeaveType
    - Create model LeaveRequestConditionApproval
    - Create model LeaverequestComment
    - Add field leave_type_id to leaverequest
    - Add field modified_by to leaverequest
    - Create model LeaveGeneralSetting
    - Create model LeaveallocationrequestComment
    - Add field leave_type_id to leaveallocationrequest
    - Add field modified_by to leaveallocationrequest
    - Create model Holiday
    - Create model HistoricalLeaveRequest
    - Create model HistoricalLeaveAllocationRequest
    - Create model HistoricalCompensatoryLeaveRequest
    - Create model HistoricalAvailableLeave
    - Create model CompensatoryLeaverequestComment
    - Add field leave_type_id to compensatoryleaverequest
    - Add field modified_by to compensatoryleaverequest
    - Add field leave_type_id to availableleave
    - Add field modified_by to availableleave
    - Create model CompanyLeave
    - Alter unique_together for availableleave (1 constraint(s))
Migrations for 'offboarding':
  offboarding/migrations/0001_initial.py
    - Create model EmployeeTask
    - Create model Offboarding
    - Create model OffboardingEmployee
    - Create model OffboardingStage
    - Create model ResignationLetter
    - Create model OffboardingTask
    - Create model OffboardingStageMultipleFile
    - Create model OffboardingNote
    - Create model OffboardingGeneralSetting
    - Add field stage_id to offboardingemployee
    - Create model HistoricalEmployeeTask
    - Create model ExitReason
    - Add field employee_id to employeetask
    - Add field modified_by to employeetask
    - Add field task_id to employeetask
    - Alter unique_together for employeetask (1 constraint(s))
Migrations for 'payroll':
  payroll/migrations/0001_initial.py
    - Create model Allowance
    - Create model Contract
    - Create model Deduction
    - Create model EncashmentGeneralSettings
    - Create model FilingStatus
    - Create model MultipleCondition
    - Create model OverrideAttendance
    - Create model OverrideLeaveRequest
    - Create model OverrideWorkInfo
    - Create model Reimbursement
    - Create model ReimbursementFile
    - Create model ReimbursementMultipleAttachment
    - Create model WorkRecord
    - Create model TaxBracket
    - Create model ReimbursementrequestComment
    - Add field other_attachments to reimbursement
    - Create model Payslip
    - Create model PayrollSettings
    - Create model PayrollGeneralSetting
    - Create model LoanAccount
    - Create model HistoricalPayslip
    - Create model HistoricalContract
    - Add field other_conditions to deduction
    - Add field specific_employees to deduction
    - Add field filing_status to contract
    - Add field job_position to contract
    - Add field job_role to contract
    - Add field modified_by to contract
    - Add field shift to contract
    - Add field work_type to contract
    - Add field other_conditions to allowance
    - Add field shift_id to allowance
    - Add field specific_employees to allowance
    - Add field work_type_id to allowance
    - Alter unique_together for contract (1 constraint(s))
    - Alter unique_together for allowance (1 constraint(s))
Migrations for 'pms':
  pms/migrations/0001_initial.py
    - Create model EmployeeKeyResult
    - Create model EmployeeObjective
    - Create model Feedback
    - Create model KeyResult
    - Create model Meetings
    - Create model Question
    - Create model QuestionTemplate
    - Create model QuestionOptions
    - Add field template_id to question
    - Create model Period
    - Create model Objective
    - Create model MeetingsAnswer
    - Add field question_template to meetings
    - Create model KeyResultFeedback
    - Create model HistoricalObjective
    - Create model HistoricalKeyResult
    - Create model HistoricalEmployeeObjective
    - Create model HistoricalEmployeeKeyResult
    - Create model HistoricalComment
    - Add field question_template_id to feedback
    - Add field subordinate_id to feedback
    - Add field key_result_id to employeeobjective
    - Add field modified_by to employeeobjective
    - Add field objective_id to employeeobjective
    - Add field employee_objective_id to employeekeyresult
    - Add field key_result_id to employeekeyresult
    - Create model Comment
    - Create model Answer
    - Create model AnonymousFeedback
Migrations for 'recruitment':
  recruitment/migrations/0001_initial.py
    - Create model Candidate
    - Create model Recruitment
    - Create model SkillZone
    - Create model Stage
    - Create model StageFiles
    - Create model SurveyTemplate
    - Create model StageNote
    - Create model RejectReason
    - Create model RejectedCandidate
    - Create model RecruitmentSurveyAnswer
    - Create model RecruitmentSurvey
    - Create model RecruitmentMailTemplate
    - Create model RecruitmentGeneralSetting
    - Add field survey_templates to recruitment
    - Create model QuestionOrdering
    - Create model InterviewSchedule
    - Create model HistoricalRejectedCandidate
    - Create model HistoricalCandidate
    - Add field recruitment_id to candidate
    - Add field referral to candidate
    - Add field stage_id to candidate
    - Create model SkillZoneCandidate
    - Alter unique_together for recruitment (2 constraint(s))
    - Create model CandidateRating
    - Alter unique_together for candidate (1 constraint(s))
Migrations for 'onboarding':
  onboarding/migrations/0001_initial.py
    - Create model CandidateTask
    - Create model OnboardingStage
    - Create model OnboardingTask
    - Create model OnboardingPortal
    - Create model HistoricalCandidateTask
    - Add field onboarding_task_id to candidatetask
    - Add field stage_id to candidatetask
    - Create model CandidateStage
Migrations for 'notifications':
  notifications/migrations/0001_initial.py
    - Create model Notification
root@ip-10-10-28-15:/opt/horilla# python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, asset, attendance, auditlog, auth, base, contenttypes, django_apscheduler, django_ses, employee, helpdesk, horilla_audit, horilla_documents, leave, notifications, offboarding, onboarding, payroll, pms, recruitment, sessions
Running migrations:
  Applying auditlog.0001_initial... OK
  Applying auditlog.0002_auto_support_long_primary_keys... OK
  Applying auditlog.0003_logentry_remote_addr... OK
  Applying auditlog.0004_logentry_detailed_object_repr... OK
  Applying auditlog.0005_logentry_additional_data_verbose_name... OK
  Applying auditlog.0006_object_pk_index... OK
  Applying auditlog.0007_object_pk_type... OK
  Applying auditlog.0008_action_index... OK
  Applying auditlog.0009_alter_logentry_additional_data... OK
  Applying auditlog.0010_alter_logentry_timestamp... OK
  Applying auditlog.0011_logentry_serialized_data...Job "block_unblock_disciplinary (trigger: interval[0:00:10], next run at: 2024-05-27 09:09:37 IST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column employee_disciplinaryaction.modified_by_id does not exist
LINE 1: ...", "employee_disciplinaryaction"."created_by_id", "employee_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/horilla/employee/scheduler.py", line 29, in block_unblock_disciplinary
    for dis in dis_action:
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column employee_disciplinaryaction.modified_by_id does not exist
LINE 1: ...", "employee_disciplinaryaction"."created_by_id", "employee_...
                                                             ^

 OK
  Applying auditlog.0012_add_logentry_action_access... OK
  Applying auditlog.0013_alter_logentry_timestamp... OK
  Applying auditlog.0014_logentry_cid... OK
  Applying auditlog.0015_alter_logentry_changes... OK
```

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
Please ignore that error and proceed. In case the migration command has stopped in the first attempt, please run again. The problem is with the scheduler running in parallel with the migration command. The concern will show only once and will not show again.
Please let us know if the error still persists.

With Regards,
**Team Horilla**

**Comment by BhuviTheDataGuy** [comment]
Error.

```
Applying employee.0002_disciplinaryaction...Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateTable: relation "employee_disciplinaryaction" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/horilla/manage.py", line 22, in <module>
    main()
  File "/opt/horilla/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 451, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/schema.py", line 45, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "employee_disciplinaryaction" already exists
```

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
Have you added any data into the disciplinary action model?

With Regards,
**Team Horilla**

**Comment by BhuviTheDataGuy** [comment]
No

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
Can you try by removing the table (_employee_disciplinaryaction_) from the database using the psql query and try again as there is no data in the model ?
Only run the _migrate_ command, do not run the _makemigrations_ command.
**PS: Please take a backup of the database before removing the table from the database.**

With Regards,
**Team Horilla**

**Comment by BhuviTheDataGuy** [comment]
Can I drop with cascade? It has some dependency

**Comment by horilla-opensource** [comment]
That'll break the database most probably.
The current issue came up when you commented the _disciplinaryaction_ to recreate the model to which a new line in the migration file was created only for creating the _disciplinaryaction_ and not its dependent models.
It's better to try without the CASCADE first and if that doesn't fix the issue, we can manually remove the two dependent modules and make the migrations.

With Regards,
**Team Horilla**

**Comment by BhuviTheDataGuy** [comment]
Can you help me
I cant drop 
It’s saying depending tables are there

**Comment by horilla-opensource** [comment]
We can proceed with the CASCADE command then. In case of conflicts we can make the adjustments in the migrations file to add the dependent models.

**Comment by BhuviTheDataGuy** [comment]
```
 Applying employee.0002_disciplinaryaction...Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateTable: relation "employee_disciplinaryaction_company_id" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/horilla/manage.py", line 22, in <module>
    main()
  File "/opt/horilla/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 477, in create_model
    self.create_model(field.remote_field.through)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 451, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/schema.py", line 45, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "employee_disciplinaryaction_company_id" already exists

```

**Comment by horilla-opensource** [comment]
Didn't the cascade remove those two tables? 
![WhatsApp Image 2024-05-27 at 9 32 08 PM](https://github.com/horilla-opensource/horilla/assets/131998600/d842916a-0001-4f18-83f9-892dd98a1dde)

**Comment by BhuviTheDataGuy** [comment]
I did it,

after that im getting this error.
```
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/horilla/base/middleware.py", line 38, in __call__
    ).first()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column base_company.modified_by_id does not exist
LINE 1: ...ny"."created_at", "base_company"."created_by_id", "base_comp...
```
