### ISSUE TITLE
 RelatedObjectDoesNotExist at 

### ISSUE THREAD

**Issue by parth5757** [horilla-opensource/horilla#217]
when ever runing project i am getting the 
RelatedObjectDoesNotExist at 
User has no employee_get.

![Screenshot 2024-06-24 100433](https://github.com/horilla-opensource/horilla/assets/60839082/1bfc701a-3fd1-49c4-abf4-a58a235361a3)

Traceback (most recent call last):
  File "/workspaces/horilla/horilla/decorators.py", line 191, in wrapped_view
    func = view_func(request, *args, **kwargs)
  File "/workspaces/horilla/base/views.py", line 364, in home
    employee=request.user.employee_get
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/django/utils/functional.py", line 268, in inner
    return func(_wrapped, *args)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee_get.RelatedObjectDoesNotExist: User has no employee_get.
Internal Server Error: /
Traceback (most recent call last):
  File "/workspaces/horilla/horilla/decorators.py", line 191, in wrapped_view
    func = view_func(request, *args, **kwargs)
  File "/workspaces/horilla/base/views.py", line 364, in home
    employee=request.user.employee_get
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/django/utils/functional.py", line 268, in inner
    return func(_wrapped, *args)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee_get.RelatedObjectDoesNotExist: User has no employee_get.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspaces/horilla/horilla/decorators.py", line 196, in wrapped_view
    return view_func(request, *args, **kwargs)
  File "/workspaces/horilla/base/views.py", line 364, in home
    employee=request.user.employee_get
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/django/utils/functional.py", line 268, in inner
    return func(_wrapped, *args)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee_get.RelatedObjectDoesNotExist: User has no employee_get.
[24/Jun/2024 10:03:44] "GET / HTTP/1.1" 500 109169
Not Found: /favicon.ico

**Comment by horilla-opensource** [comment]
Hi Parth,
Did you create the admin user using the _createsuperuser_  command or _createhorillauser_ ?
To have an admin user employee in Horilla, you need to create the users using the command _createhorillauser_ .

With Regards,
**Team Horilla**

**Comment by parth5757** [comment]
Thank You
