### ISSUE TITLE
Module not found frontend

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [horilla-opensource/horilla#222]
I have pulled the recent code and tried to run the migrate command, this gives me the following error.

```
Traceback (most recent call last):
  File "/opt/horilla/manage.py", line 22, in <module>
    main()
  File "/opt/horilla/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/dist-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/horilla/biometric/apps.py", line 24, in ready
    from horilla.urls import urlpatterns
  File "/opt/horilla/horilla/urls.py", line 33, in <module>
    path("recruitment/", include("recruitment.urls")),
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/horilla/recruitment/urls.py", line 27, in <module>
    from recruitment.views import views
  File "/opt/horilla/recruitment/views/views.py", line 24, in <module>
    import fitz
  File "/usr/local/lib/python3.10/dist-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'
```

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
It is an issue with a missing package dependency.
There is a new python package to be installed.
It is updated in the requirements.txt file.
Please run `pip3 install -r requirements.txt` or `pip3 install PyMuPDF`

With Regards,
**Team Horilla**

**Comment by BhuviTheDataGuy** [comment]
solved, thanks
