### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by ImtiazEvan720** [horilla-opensource/horilla#227]
Docker build keeps on restarting with the following output

[2024-06-27 16:24:37 +0530] [64] [ERROR] Exception in worker process
server-1  | Traceback (most recent call last):
server-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
server-1  |     worker.init_process()
server-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
server-1  |     self.load_wsgi()
server-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
server-1  |     self.wsgi = self.app.wsgi()
server-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
server-1  |     self.callable = self.load()
server-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
server-1  |     return self.load_wsgiapp()
server-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
server-1  |     return util.import_app(self.app_uri)
server-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
server-1  |     mod = importlib.import_module(module)
server-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
server-1  |     return _bootstrap._gcd_import(name[level:], package, level)
server-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
server-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
server-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
server-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
server-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
server-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
server-1  |   File "/app/horilla/wsgi.py", line 16, in <module>
server-1  |     application = get_wsgi_application()
server-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
server-1  |     django.setup(set_prefix=False)
server-1  |   File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
server-1  |     apps.populate(settings.INSTALLED_APPS)
server-1  |   File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
server-1  |     app_config.ready()
server-1  |   File "/app/biometric/apps.py", line 24, in ready
server-1  |     from horilla.urls import urlpatterns
server-1  |   File "/app/horilla/urls.py", line 33, in <module>
server-1  |     path("recruitment/", include("recruitment.urls")),
server-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
server-1  |     urlconf_module = import_module(urlconf_module)
server-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
server-1  |     return _bootstrap._gcd_import(name[level:], package, level)
server-1  |   File "/app/recruitment/urls.py", line 27, in <module>
server-1  |     from recruitment.views import views
server-1  |   File "/app/recruitment/views/views.py", line 24, in <module>
server-1  |     import fitz
server-1  |   File "/usr/local/lib/python3.10/site-packages/fitz/__init__.py", line 2, in <module>
server-1  |     from pymupdf import *
server-1  |   File "/usr/local/lib/python3.10/site-packages/pymupdf/__init__.py", line 29, in <module>
server-1  |     from . import extra
server-1  |   File "/usr/local/lib/python3.10/site-packages/pymupdf/extra.py", line 10, in <module>
server-1  |     from . import _extra
server-1  | ImportError: libmupdf.so.24.4: cannot open shared object file: No such file or directory
server-1  | [2024-06-27 16:24:37 +0530] [64] [INFO] Worker exiting (pid: 64)
server-1  | [2024-06-27 10:54:38 +0000] [63] [ERROR] Worker (pid:64) exited with code 3
server-1  | [2024-06-27 10:54:38 +0000] [63] [ERROR] Shutting down: Master
server-1  | [2024-06-27 10:54:38 +0000] [63] [ERROR] Reason: Worker failed to boot.

**Comment by horilla-opensource** [comment]
Hi @ImtiazEvan720 ,
Can you explain the steps you have followed to run the docker build ?

With Regards,
**Team Horilla**

**Comment by ImtiazEvan720** [comment]
I'm trying to run the project on a mac using docker. Here are my steps,
1. clone project from github
2. cd to directory using from terminal
3. use docker-compose to build images with command "docker-compose build"
3.  then run the containers from the image using command "docker-compose up"

the project was running fine using docker before, idk what happened recently. I've done whatever possible on my end , reset my mac with a fresh installation of docker and re-downloaded the project from git.
any suggestions would be greatly appreciated.

**Comment by horilla-opensource** [comment]
From the error log and methods followed, I think that it is because of a missing package.
Can you install the following package and try again ?
`pip3 install PyMuPDF`
Since you are using the docker method, please enter into the docker shell and install the package inside the docket bash.
Please let us know after trying this out.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Is the package installed inside the docker container ?

**Comment by ImtiazEvan720** [comment]
pip list command shows,

PyMuPDF               1.24.7
PyMuPDFb              1.24.6
which implies it's installed already. Can you verify if you can build and run the docker image on your end without any issues ?

**Comment by horilla-opensource** [comment]
Hi @ImtiazEvan720 ,
Sorry for the inconvenience caused. We were able to reproduce the error at our end. Our team is working on the solution for the same. 
Will update you asap once the solution is deployed.

With Regards,
**Team Horilla**

**Comment by ImtiazEvan720** [comment]
Thank you so much for the prompt reply and really appreciate the support.

**Comment by ImtiazEvan720** [comment]
Hi @horilla-opensource , any update on the issue , since I'm using docker to build and run the project I'm stuck at the moment. Do let me know if there's a quick work around.

**Comment by horilla-opensource** [comment]
Hi @ImtiazEvan720 ,
Will update you once we have found the solution to it.

With Regards,

**Comment by horilla-opensource** [comment]
Hi @ImtiazEvan720 ,
Can you please confirm the OS you are using?
I was able to successfully run the docker image in my ubuntu system, but faced the above issue on my macOS. 
I would like to confirm your OS for further clarification.

With Regards,
**Team Horilla**

**Comment by ImtiazEvan720** [comment]
I'm using macOS sonoma(14.3.1)

**Comment by horilla-opensource** [comment]
The issue is only coming up in MacOS docker builds.
The team is working on the solution for it.

**Comment by horilla-opensource** [comment]
Hi @ImtiazEvan720 ,
The solution for the build fail is now updated in the master code base.
The issue was with the latest PyMuPDF package for MacOS ([ImportError: libmupdf.so.24.4: cannot open shared object file: No such file or directory](https://github.com/pymupdf/PyMuPDF/issues/3643).
The required version of PyMuPDF for Horilla is lowered to the stable 1.24.5 and is now working fine.
Please check and let us know if you face any more issues.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @ImtiazEvan720 ,
Were you able to test out the solution?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @ImtiazEvan720 ,
We are closing this issue due to inactivity. It seems that there hasn't been any recent activity or discussion, and we believe it may have been resolved or is no longer relevant. 
If you feel this issue is still important and should be addressed, please feel free to reopen it or create a new issue with updated details. 

With Regards,
**Team Horilla**
