### ISSUE TITLE
Updating to last master changes

### ISSUE THREAD

**Issue by zgurea1** [horilla-opensource/horilla#258]
# Bug Report

## Description

Hi, after updating to last master changes is giving the error bellow, what can be the issue?

## Steps to Reproduce

1. git pull the last changes
2. docker compose up -d 

## Expected Behavior

To start the app

## Actual Behavior

[2024-07-23 07:20:09 +0000] [63] [INFO] Starting gunicorn 22.0.0

[2024-07-23 07:20:09 +0000] [63] [INFO] Listening at: http://0.0.0.0:8000 (63)

[2024-07-23 07:20:09 +0000] [63] [INFO] Using worker: sync

[2024-07-23 07:20:09 +0000] [64] [INFO] Booting worker with pid: 64

[2024-07-23 12:50:11 +0530] [64] [ERROR] Exception in worker process

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker

    worker.init_process()

  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process

    self.load_wsgi()

  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi

    self.wsgi = self.app.wsgi()

  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi

    self.callable = self.load()

  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load

    return self.load_wsgiapp()

  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp

    return util.import_app(self.app_uri)

  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app

    mod = importlib.import_module(module)

  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/app/horilla/wsgi.py", line 16, in <module>

    application = get_wsgi_application()

  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application

    django.setup(set_prefix=False)

  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate

    app_config.ready()

  File "/app/biometric/apps.py", line 24, in ready

    from horilla.urls import urlpatterns

  File "/app/horilla/urls.py", line 22, in <module>

    from base.views import home, login_user, logout_user

  File "/app/base/views.py", line 33, in <module>

    from attendance.forms import AttendanceValidationConditionForm

  File "/app/attendance/forms.py", line 39, in <module>

    from attendance.filters import AttendanceFilters

  File "/app/attendance/filters.py", line 24, in <module>

    from base.filters import FilterSet

  File "/app/base/filters.py", line 18, in <module>

    from horilla.filters import FilterSet, filter_by_name

  File "/app/horilla/filters.py", line 13, in <module>

    from base.methods import reload_queryset

  File "/app/base/methods.py", line 19, in <module>

    from xhtml2pdf import pisa

  File "/usr/local/lib/python3.10/site-packages/xhtml2pdf/pisa.py", line 26, in <module>

    from xhtml2pdf.document import pisaDocument

  File "/usr/local/lib/python3.10/site-packages/xhtml2pdf/document.py", line 25, in <module>

    from xhtml2pdf.context import pisaContext

  File "/usr/local/lib/python3.10/site-packages/xhtml2pdf/context.py", line 39, in <module>

    from xhtml2pdf import default, parser

  File "/usr/local/lib/python3.10/site-packages/xhtml2pdf/parser.py", line 44, in <module>

    from xhtml2pdf.tables import (  # noqa: F401

  File "/usr/local/lib/python3.10/site-packages/xhtml2pdf/tables.py", line 21, in <module>

    from xhtml2pdf.tags import pisaTag

  File "/usr/local/lib/python3.10/site-packages/xhtml2pdf/tags.py", line 35, in <module>

    from xhtml2pdf.charts import (

  File "/usr/local/lib/python3.10/site-packages/xhtml2pdf/charts.py", line 7, in <module>

    from xhtml2pdf.util import getColor

  File "/usr/local/lib/python3.10/site-packages/xhtml2pdf/util.py", line 25, in <module>

    from bidi.algorithm import get_display

ModuleNotFoundError: No module named 'bidi.algorithm'

**Note:** _Remember to search through existing issues before submitting a new one to ensure that the issue hasn't been reported already. Provide as much information as possible to help the maintainers understand and address the problem effectively._

**Comment by horilla-opensource** [comment]
HI @zgurea1 ,
This is a default which comes with the PyMuPDF package. We are confirming the issue from our end.
Meanwhile can you install the package inside the docker container using the command:
```
pip3 install python-bidi
```

**Comment by zgurea1** [comment]
@horilla-opensource that worked, thx.
