### ISSUE TITLE
Cannot create leave request for another user

### ISSUE THREAD

**Issue by sergej-wv** [horilla-opensource/horilla#310]
# Bug Report

## Description

An error is being displayed when creating a leave request for another user.

## Steps to Reproduce

1. create leave request for another user

## Expected Behavior

A leave request is created.

## Actual Behavior

Error 500 returned.

## Screenshots

<img width="1436" alt="Bildschirmfoto 2024-09-02 um 08 56 25" src="https://github.com/user-attachments/assets/87903b19-619e-4eec-8af6-372c3bb67462">

## Environment

- **Django Version:** 4.2.11
- **Python Version:** 3.10
- **Operating System:** Ubuntu 22.04
- **Browser:** Chrome

## Additional Information

Log entries:
<details>

```
'2024-08'
Traceback (most recent call last):
  File "/opt/horilla/horilla/horilla/decorators.py", line 143, in wrapped_view
    func = view_func(request, *args, **kwargs)
  File "/opt/horilla/horilla/horilla/decorators.py", line 159, in wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/horilla/horilla/horilla/decorators.py", line 113, in _function
    return function(request, *args, **kwargs)
  File "/opt/horilla/horilla/leave/views.py", line 295, in leave_request_creation
    if form.is_valid():
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 434, in full_clean
    self._clean_form()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 455, in _clean_form
    cleaned_data = self.clean()
  File "/opt/horilla/horilla/leave/forms.py", line 302, in clean
    total_leave_days += forcasted_leaves[item]
KeyError: '2024-08'
Internal Server Error: /leave/request-creation
Traceback (most recent call last):
  File "/opt/horilla/horilla/horilla/decorators.py", line 143, in wrapped_view
    func = view_func(request, *args, **kwargs)
  File "/opt/horilla/horilla/horilla/decorators.py", line 159, in wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/horilla/horilla/horilla/decorators.py", line 113, in _function
    return function(request, *args, **kwargs)
  File "/opt/horilla/horilla/leave/views.py", line 295, in leave_request_creation
    if form.is_valid():
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 434, in full_clean
    self._clean_form()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 455, in _clean_form
    cleaned_data = self.clean()
  File "/opt/horilla/horilla/leave/forms.py", line 302, in clean
    total_leave_days += forcasted_leaves[item]
KeyError: '2024-08'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/horilla/horilla/horilla/decorators.py", line 148, in wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/horilla/horilla/horilla/decorators.py", line 159, in wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/horilla/horilla/horilla/decorators.py", line 113, in _function
    return function(request, *args, **kwargs)
  File "/opt/horilla/horilla/leave/views.py", line 295, in leave_request_creation
    if form.is_valid():
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 434, in full_clean
    self._clean_form()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 455, in _clean_form
    cleaned_data = self.clean()
  File "/opt/horilla/horilla/leave/forms.py", line 302, in clean
    total_leave_days += forcasted_leaves[item]
KeyError: '2024-08'
[02/Sep/2024 09:05:53] "POST /leave/request-creation?search=&search_field=&csrfmiddlewaretoken=qHpzLycjBi5xi68BytsJminH7M8J0O5dt5Gzrqvq4BbjHa6I76c8N82zBSlf10uA&id=&start_date=&end_date=&status=&from_date=&to_date=&field= HTTP/1.0" 500 144866
```
</details>

## Labels

bug

## Priority

medium

**Note:** _Remember to search through existing issues before submitting a new one to ensure that the issue hasn't been reported already. Provide as much information as possible to help the maintainers understand and address the problem effectively._

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
Just to confirm the issue, can you try changing the date format in the settings and try applying the leave again ?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
We can see some changes from our code and the code that you are using.
From the log, the error is being raised from the line _total_leave_days += forcasted_leaves[item]_ which is not available in our code.
We think you have made some changes in the code base.  Please update the code to _total_leave_days += forcasted_leaves_ and try again. The extra _[item]_ is causing the issue.

PS: We apologize for the typo in the code terms. We'll update the correct spelling for the forecast leaves.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
The issue was already fixed from this commit ([[UPDT] LEAVE: Added htmx for available days message display in leave request](https://github.com/horilla-opensource/horilla/commit/aa6f72a6ff7c4ae182f57c3b75808e876277ed62))

From the details, you have shared the code seems to be an older version.

Please test it out with the latest code. 
We apologize for the typo in the code terms. We'll update it on the coming commits.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
We are closing this issue due to inactivity. It seems that there hasn't been any recent activity or discussion, and we believe it may have been resolved or is no longer relevant. 
If you feel this issue is still important and should be addressed, please feel free to reopen it or create a new issue with updated details. 

With Regards,
**Team Horilla**
