### ISSUE TITLE
Employees Cannot Create Leave Requests

### ISSUE THREAD

**Issue by centaurusgod** [horilla-opensource/horilla#312]
# Bug Report
Employees who are not superadmin are unable to create a new Leave Request. Even after the permission of leave is asigned to them the issue persists. 

## Description

Whenever employees(not superadmin) tries to create Leave request, the application gets stucked on white loading screen.

## Steps to Reproduce
1. Login as normal employee (not superuser)
2. Go to Leave-> My Leave Requests -> Create Leave Requests -> Save

## Expected Behavior
The web application should have saved the leave request.

## Actual Behavior
Stucked on white loading screen

## Screenshots
![image](https://github.com/user-attachments/assets/78475d8c-5143-4cb1-81a5-e5c1ff2781c7)

## Additional Information

[03/Sep/2024 16:16:48] "GET /leave/user-request-view/ HTTP/1.1" 200 242922
[03/Sep/2024 16:16:48] "GET /employee/get-language-code/ HTTP/1.1" 200 23
[03/Sep/2024 16:16:49] "GET /inbox/notifications/api/unread_list/?max=5 HTTP/1.1" 200 1241
[03/Sep/2024 16:16:50] "GET /leave/leave-request-create?confirm=&pd= HTTP/1.1" 200 7679
[03/Sep/2024 16:16:50] "GET /get-horilla-installed-apps/ HTTP/1.1" 200 582
[03/Sep/2024 16:16:52] "GET /leave/employee-available-leave-count?employee_id=2&requested_days=&start_date=2024-09-03&start_date_breakdown=full_day&end_date=2024-09-03&end_date_breakdown=full_day&description=&leave_type_id=2 HTTP/1.1" 200 473
[03/Sep/2024 16:16:52] "GET /get-horilla-installed-apps/ HTTP/1.1" 200 582
[03/Sep/2024 16:16:54] "GET /leave/check-interview-conflicts?start_date=2024-09-03&end_date=2024-09-03&employee_id=2 HTTP/1.1" 200 18
'NoneType' object has no attribute 'enabled'
Internal Server Error: /leave/leave-request-create
Traceback (most recent call last):
  File "C:\Users\I_M_Machine\Desktop\horilla-master\horilla\decorators.py", line 234, in wrapped_view
    func = view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I_M_Machine\Desktop\horilla-master\horilla\decorators.py", line 260, in wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I_M_Machine\Desktop\horilla-master\leave\views.py", line 2900, in leave_request_create
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\forms\forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\forms\forms.py", line 196, in errors
    self.full_clean()
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\forms\forms.py", line 435, in full_clean
    self._post_clean()
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\forms\models.py", line 486, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\db\models\base.py", line 1477, in full_clean
    self.clean()
  File "C:\Users\I_M_Machine\Desktop\horilla-master\leave\models.py", line 733, in clean
    if EmployeePastLeaveRestrict.objects.first().enabled:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'enabled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I_M_Machine\Desktop\horilla-master\horilla\decorators.py", line 249, in wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I_M_Machine\Desktop\horilla-master\horilla\decorators.py", line 260, in wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I_M_Machine\Desktop\horilla-master\leave\views.py", line 2900, in leave_request_create
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\forms\forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\forms\forms.py", line 196, in errors
    self.full_clean()
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\forms\forms.py", line 435, in full_clean
    self._post_clean()
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\forms\models.py", line 486, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "C:\Users\I_M_Machine\anaconda3\envs\hrms\Lib\site-packages\django\db\models\base.py", line 1477, in full_clean
    self.clean()
  File "C:\Users\I_M_Machine\Desktop\horilla-master\leave\models.py", line 733, in clean
    if EmployeePastLeaveRestrict.objects.first().enabled:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'enabled'

## Possible Solution
Removing .enabled from horilla-master/leave/models.py 
Line number 733:
From
`            if EmployeePastLeaveRestrict.objects.first().enabled:
                if self.start_date < date.today():
                    raise ValidationError(_("Requests cannot be made for past dates."))`
               
To
`            if EmployeePastLeaveRestrict.objects.first():
                if self.start_date < date.today():
                    raise ValidationError(_("Requests cannot be made for past dates."))`

## Priority
High

## Assignees
@horilla-opensource

**Comment by horilla-opensource** [comment]
Hi @centaurusgod ,
The solution is updated in the latest commit. Please pull the code from the master and try again.

Please let us know if you have any questions or concerns.

With Regards,
**Team Horilla**

**Comment by centaurusgod** [comment]
I have pulled the code and applied migrations but the issue isn't fixed.
![image](https://github.com/user-attachments/assets/d24e5aaf-92ad-4a30-97df-6a65a11904e4)
