### ISSUE TITLE
I have updated to the new version. and I have the old database.  The program don't work.

### ISSUE THREAD

**Issue by edmir31** [horilla-opensource/horilla#317]
I have updated to the new files. and I have the old database.  My site gives me this error.

OperationalError at /
no such column: base_employeeshiftschedule.is_auto_punch_out_enabled
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Django Version:	4.2.11
Exception Type:	OperationalError
Exception Value:	
no such column: base_employeeshiftschedule.is_auto_punch_out_enabled
Exception Location:	C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py, line 328, in execute
Raised during:	horilla.decorators.wrapped_view
Python Executable:	C:\Users\User\AppData\Local\Programs\Python\Python312\python.exe
Python Version:	3.12.3
Python Path:	
['C:\\Users\\User\\Desktop\\horilla2024\\horilla',
 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\python312.zip',
 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\DLLs',
 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib',
 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312',
 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages']
Server time:	Wed, 04 Sep 2024 14:53:31 +0530

Request Method: | GET
-- | --
http://127.0.0.1:8000/
4.2.11
OperationalError
no such column: base_employeeshiftschedule.is_auto_punch_out_enabled
C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py, line 328, in execute
horilla.decorators.wrapped_view
C:\Users\User\AppData\Local\Programs\Python\Python312\python.exe
3.12.3
['C:\\Users\\User\\Desktop\\horilla2024\\horilla',  'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\python312.zip',  'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\DLLs',  'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib',  'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312',  'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages']
Wed, 04 Sep 2024 14:53:31 +0530

</body>
</html>

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/

Django Version: 4.2.11
Python Version: 3.12.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'notifications',
 'mathfilters',
 'corsheaders',
 'simple_history',
 'django_filters',
 'base',
 'employee',
 'recruitment',
 'leave',
 'pms',
 'onboarding',
 'asset',
 'attendance',
 'payroll',
 'widget_tweaks',
 'django_apscheduler',
 'horilla_audit',
 'horilla_widgets',
 'horilla_crumbs',
 'horilla_documents',
 'haystack',
 'horilla_views',
 'horilla_automations',
 'auditlog',
 'biometric',
 'helpdesk',
 'offboarding']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'auditlog.middleware.AuditlogMiddleware',
 'base.middleware.CompanyMiddleware',
 'horilla.horilla_middlewares.MethodNotAllowedMiddleware',
 'horilla.horilla_middlewares.ThreadLocalMiddleware',
 'attendance.middleware.AttendanceMiddleware']

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The above exception (no such column: base_employeeshiftschedule.is_auto_punch_out_enabled) was the direct cause of the following exception:
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\horilla2024\horilla\attendance\middleware.py", line 11, in process_request
    self.trigger_function()
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\horilla2024\horilla\attendance\middleware.py", line 22, in trigger_function
    for shift_schedule in automatic_check_out_shifts:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: OperationalError at /
Exception Value: no such column: base_employeeshiftschedule.is_auto_punch_out_enabled

**Comment by horilla-opensource** [comment]
Hi @edmir31 ,
Can you please share the content of the last migration file in the base app?

With Regards,
**Team Horilla**

**Comment by centaurusgod** [comment]
@edmir31 
Have you applied necessary migrations after updating the files? 

1. `python manage.py makemigrations`
2. `python manage.py migrate`

**Comment by edmir31** [comment]
> @edmir31 Have you applied necessary migrations after updating the files?
> 
> 1. `python manage.py makemigrations`
> 2. `python manage.py migrate`

Yes i have done theme.
Some tables have missing columns.

base_employeeshiftschedule.is_auto_punch_out_enabled
base_rotatingworktypeassign.additional_data
 base_rotatingshiftassign.additional_data
 base_rotatingworktypeassign.additional_data 

Can I add them manually.

**Comment by edmir31** [comment]
> Hi @edmir31 , Can you please share the content of the last migration file in the base app?
> 
> With Regards, **Team Horilla**


I have done.
python manage.py makemigrations
python manage.py migrate

Some tables have missing columns.
base_employeeshiftschedule.is_auto_punch_out_enabled
base_rotatingworktypeassign.additional_data
 base_rotatingshiftassign.additional_data
 base_rotatingworktypeassign.additional_data 

Can I add them manually in the database. I'm using sqlite.

**Comment by horilla-opensource** [comment]
Hi @edmir31 ,
Directly adding the tables to the database is not suggested as it might cause issues with the migrations.
It's better to add the missing table details in the last migration file of the base and run the migrate command.

**Comment by edmir31** [comment]
> Hi @edmir31 , Directly adding the tables to the database is not suggested as it might cause issues with the migrations. It's better to add the missing table details in the last migration file of the base and run the migrate command.

Hi @horilla-opensource 
Can you explain how can i check using migration what tables and columns are missing. And where to check.  I have found the missing tables by the errors.

**Comment by stevenfamy** [comment]
This was also happening to us, we're using 1.2.0 and want to trying the Master branch with latest changes, when starting the apps there was no migration applied but cannot accessing the web because some columns are missing, is there any work around?

**Comment by horilla-opensource** [comment]
> > Hi @edmir31 , Directly adding the tables to the database is not suggested as it might cause issues with the migrations. It's better to add the missing table details in the last migration file of the base and run the migrate command.
> 
> Hi @horilla-opensource Can you explain how can i check using migration what tables and columns are missing. And where to check. I have found the missing tables by the errors.

Hi  @edmir31 ,
Sorry for the late reply. 
Please check the missing model names inside the migrations file we mentioned above and comment that section.
After that run the `migrate` command. Once migrated, run the `makemigrations` and `migrate` command again.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
> This was also happening to us, we're using 1.2.0 and want to trying the Master branch with latest changes, when starting the apps there was no migration applied but cannot accessing the web because some columns are missing, is there any work around?

Hi @stevenfamy ,
Can you specify in which model you are having the issue? Can you please share the error logs?

With Regards,
**Team Horilla**

**Comment by stevenfamy** [comment]
> > This was also happening to us, we're using 1.2.0 and want to trying the Master branch with latest changes, when starting the apps there was no migration applied but cannot accessing the web because some columns are missing, is there any work around?
> 
> Hi @stevenfamy , Can you specify in which model you are having the issue? Can you please share the error logs?
> 
> With Regards, **Team Horilla**

Hi thanks for the reply, the errors was the same as @edmir31 missing columns base_employeeshiftschedule.is_auto_punch_out_enabled

**Comment by edmir31** [comment]
When i roon the migration comand it says.

My migartion files : https://gofile.io/d/MHZFs5

 manage.py makemigrations
No changes detected


manage.py migrate
Operations to perform:
  Apply all migrations: admin, asset, attendance, auditlog, auth, base, biometric, contenttypes, django_apscheduler, employee, helpdesk, horilla_audit, horilla_automations, horilla_documents, horilla_views, leave, notifications, offboarding, onboarding, payroll, pms, recruitment, sessions
Running migrations:
  No migrations to apply.

Nothing changes. 

I see i have some rows and some tables differently in my old database old database 302 tables new database 317 tables.
I there way to  update the old database to the new.

**Comment by horilla-opensource** [comment]
Hi @edmir31 @stevenfamy ,
Can we connect with our team on skype if possible to discuss further on this issue?
Please connect with us on skype at _**support@horilla.com**_ or _**teamhorilla@gmail.com**_.

**Comment by horilla-opensource** [comment]
Hi @edmir31 ,
We are closing this issue due to inactivity. It seems that there hasn't been any recent activity or discussion, and we believe it may have been resolved or is no longer relevant. 
If you feel this issue is still important and should be addressed, please feel free to reopen it or create a new issue with updated details. 

With Regards,
**Team Horilla**
