### ISSUE TITLE
 raise FullResultSet django.core.exceptions.FullResultSet with sql server database 

### ISSUE THREAD

**Issue by MagloireKITIO** [horilla-opensource/horilla#360]
Hello, I have This error when i want to make migration on sql server database 

python manage.py makemigrations 
(0.140) QUERY = "SELECT CAST(SERVERPROPERTY('ProductVersion') AS varchar)" - PARAMS = (); args=None; alias=default
(0.125) QUERY = 'SELECT SYSDATETIME()' - PARAMS = (); args=None; alias=default
(0.140) QUERY = "SELECT CAST(SERVERPROPERTY('ProductVersion') AS varchar)" - PARAMS = (); args=None; alias=default
(0.141) QUERY = 'SELECT SYSDATETIME()' - PARAMS = (); args=None; alias=default
(0.125) QUERY = 'SET NOCOUNT OFF; UPDATE [biometric_biometricdevices] SET [is_live] = %s' - PARAMS = (0,); args=(False,); alias=default
(0.172) QUERY = 'SELECT TABLE_NAME, TABLE_TYPE FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = SCHEMA_NAME()' - PARAMS = (); args=None; alias=default
Traceback (most recent call last):
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\manage.py", line 22, in <module>
    main()
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute   
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\core\management\base.py", line 412, in run_from_argv 
    self.execute(*args, **cmd_options)
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\core\management\base.py", line 458, in execute       
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\core\management\base.py", line 106, in wrapper       
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\core\management\commands\makemigrations.py", line 158, in handle
    loader.check_consistent_history(connection)
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\db\migrations\loader.py", line 313, in check_consistent_history
    applied = recorder.applied_migrations()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\db\migrations\recorder.py", line 82, in applied_migrations
    return {
           ^
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all        
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1549, in execute_sql    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\sql_server\pyodbc\compiler.py", line 189, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\sql_server\pyodbc\compiler.py", line 358, in compile        
    return super().compile(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 546, in compile     
    sql, params = node.as_sql(self, self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stage.dsi.pmo\Documents\Projet Dev\Activa Hr\activahr\.venv\Lib\site-packages\django\db\models\sql\where.py", line 174, in as_sql
    raise FullResultSet
django.core.exceptions.FullResultSet

**Comment by horilla-opensource** [comment]
Hi @MagloireKITIO Were you able to work around with this issue?

**Comment by horilla-opensource** [comment]
Hi @MagloireKITIO ,

We are closing this issue due to inactivity. It seems that there hasn't been any recent activity or discussion, and we believe it may have been resolved or is no longer relevant. 
If you feel this issue is still important and should be addressed, please feel free to reopen it or create a new issue with updated details. 

With Regards,
**Team Horilla**
