### ISSUE TITLE
Arguments: (AttributeError("'NoneType' object has no attribute 'auto_approve_ot'"),)

### ISSUE THREAD

**Issue by vanyell** [horilla-opensource/horilla#365]
# Bug Report
Upgrade to latest release, zk biometric attendance broke

Arguments: (AttributeError("'NoneType' object has no attribute 'auto_approve_ot'"),)

## Steps to Reproduce

1. _[Detailed step-by-step instructions to reproduce the issue.]_

created a new DB , started from scratch.
imported users and inserted into the biometric attendance table the users
enabled schedule polling from zkteco biometric device

## Expected Behavior

Attendance checkin/checkout gets recorded.

## Actual Behavior
running application using python manage.py runserver in debug mode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sysadm/repo/horilla/venv/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/sysadm/repo/horilla/biometric/views.py", line 2003, in <lambda>
    lambda: zk_biometric_device_attendance(device.id),
  File "/home/sysadm/repo/horilla/biometric/views.py", line 1859, in zk_biometric_device_attendance
    logger.error("Got an error : ", error)
Message: 'Got an error : '
Arguments: (AttributeError("'NoneType' object has no attribute 'auto_approve_ot'"),)
^CException ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1553, in _shutdown
    atexit_call()
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/lib/python3.11/threading.py", line 1112, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):


## Screenshots

![image](https://github.com/user-attachments/assets/e74af1a8-57eb-4bd6-a0d4-092b0b54d256)


## Environment

- **Django Version:** _[Django version you're using, e.g., 3.2.1]_
- **Python Version:** 3.11
- **Operating System:** debian 10
- **Browser:** _[If applicable, specify the browser and version you're using.]_

**Comment by vanyell** [comment]
No issue to resolve
