### ISSUE TITLE
RelatedObjectDoesNotExist at /login/

### ISSUE THREAD

**Issue by Arean82** [horilla-opensource/horilla#447]
# Bug Report

## Description

after install I logged in with the user horilla and is getting the error
Environment:

Request Method: POST
Request URL: http://192.168.157.130:3301/login/?next=/

Django Version: 4.2.11
Python Version: 3.12.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'notifications',
 'mathfilters',
 'corsheaders',
 'simple_history',
 'django_filters',
 'base',
 'employee',
 'recruitment',
 'leave',
 'pms',
 'onboarding',
 'asset',
 'attendance',
 'payroll',
 'widget_tweaks',
 'django_apscheduler',
 'accessibility',
 'horilla_audit',
 'horilla_widgets',
 'horilla_crumbs',
 'horilla_documents',
 'haystack',
 'horilla_views',
 'horilla_automations',
 'auditlog',
 'biometric',
 'helpdesk',
 'offboarding']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'auditlog.middleware.AuditlogMiddleware',
 'base.middleware.CompanyMiddleware',
 'horilla.horilla_middlewares.MethodNotAllowedMiddleware',
 'horilla.horilla_middlewares.ThreadLocalMiddleware',
 'accessibility.middlewares.AccessibilityMiddleware',
 'attendance.middleware.AttendanceMiddleware']

Traceback (most recent call last):
  File "/data/horilla/horillaenv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/data/horilla/horillaenv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/horilla/base/views.py", line 557, in login_user
    if user.employee_get.is_active == False:
       ^^^^^^^^^^^^^^^^^
  File "/data/horilla/horillaenv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
    ^

Exception Type: RelatedObjectDoesNotExist at /login/
Exception Value: User has no employee_get.

## Steps to Reproduce

Installed horilla
ran 
 gunicorn --workers 3 --bind 192.168.157.130:3301 horilla.wsgi:application
in the browser I tried to login with the user horilla
![horilla](https://github.com/user-attachments/assets/4b88fca9-6598-47cb-a9fc-97dbcb42c6d9)

then I went back and clicked on initialize database. 
getting error that password is wrong
![Screenshot (4)](https://github.com/user-attachments/assets/7b7ca849-273e-44ff-a9ca-f0988b440197)

I am able to login with the user detail via psql
root@vmtest:/data# psql -U horilla_user -h localhost -d horilla_db
Password for user horilla_user:
psql (17.2 (Ubuntu 17.2-1.pgdg24.04+1))
Type "help" for help.

horilla_db=>

## Expected Behavior

_[What you expected to happen.]_

## Actual Behavior

_[What actually happened.]_

## Screenshots

_[If applicable, provide screenshots illustrating the issue.]_

## Environment

- **Django Version:** _[Django version you're using, e.g., 3.2.1]_
- **Python Version:** _[Python version, e.g., 3.9]_
- **Operating System:** _[Your OS, e.g., Windows 10, Ubuntu 20.04]_
- **Browser:** _[If applicable, specify the browser and version you're using.]_

## Additional Information

_[Any other relevant information, logs, error messages, or context that might help in understanding and fixing the issue.]_

## Possible Solution

_[If you have any ideas or suggestions on how to fix the issue, feel free to provide them here. This is optional.]_

## Labels

_[If your project uses labels, suggest any labels that might apply to this issue, such as 'bug', 'needs investigation', etc.]_

## Priority

_[Specify the priority level for this issue, such as 'high', 'medium', 'low', etc.]_

## Assignees

_[If you want to suggest an assignee or tag a specific person to look into this issue, mention their GitHub username here.]_

## Related Issues

_[If there are any related issues or pull requests, mention them here. This is optional.]_

**Note:** _Remember to search through existing issues before submitting a new one to ensure that the issue hasn't been reported already. Provide as much information as possible to help the maintainers understand and address the problem effectively._

**Comment by Bsakwa** [comment]
Hello @Arean82 I understand how frustrating this can be. I've had a somewhat similar and recurring problem. My application launches fine until hours later when suddenly it terminates connection to the db and suddenly my db does not exist. Could be a docker issue I presume but I eventually had to manually create the database in my docker container, run the migrations once more. It fixed the problem but am still monitoring to see how it fairs.  Am not sure how you are deploying your application but share details and I would be happy to give my 2 cents.

**Comment by horilla-opensource** [comment]
Hi @Arean82,

Thank you for reporting this issue! The `RelatedObjectDoesNotExist` error occurs when a user is created without an associated employee. This often happens if you use Django's default `createsuperuser` command to create a user, as it doesn't handle the employee relationship required by our system.

To resolve this, we’ve introduced a custom management command:

`python manage.py createhorillauser`

This command ensures that the user is created with an associated employee, preventing the error. Please use this command for creating users instead of `createsuperuser`.

We’ve also fixed this issue in the source code to improve the experience. Let us know if you need further assistance!

With Regards,
Team Horilla

**Comment by Arean82** [comment]
It worked now, but the issue is now. If someone uses the gorilla user, they would be able to view the page with the error `Exception Type: RelatedObjectDoesNotExist at /login/`. This is a security risk, as this page shows the configuration and system details to the public. 
so we need to remove the user gorilla now. using the mentioned command I created a user named admin. Now, the user `horilla `is not showing in Ui for the list of users. So how do I remove the user horilla? 
If I should remove the user from the database, how should I do it? I mean, which table contains the details?

**Comment by horilla-opensource** [comment]
Hi @Arean82 ,

Here’s how you can remove the user `horilla` using the Django Admin page:

1. **Access the Admin Panel**  
   - Navigate to [http://127.0.0.1:8000/admin/auth/user/](http://127.0.0.1:8000/admin/auth/user/).  
   - Log in using your superuser credentials.  

2. **Find the User**  
   - Search for the user `horilla`  in the list of users.  

3. **Delete the User**  
   - Select the checkbox next to `horilla`.  
   - In the "Actions" dropdown menu, choose **Delete selected users**.  
   - Click **Go** and confirm the deletion when prompted.  

Let me know if you need further assistance!

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @Arean82,

We are closing this issue due to inactivity. It seems that there hasn't been any recent activity or discussion, and we believe it may have been resolved or is no longer relevant. 
If you feel this issue is still important and should be addressed, please feel free to reopen it or create a new issue with updated details.

With Regards,
**Team Horilla**
