### ISSUE TITLE
Python import error after update

### ISSUE THREAD

**Issue by sergej-wv** [horilla-opensource/horilla#79]
# Bug Report

## Description

Hello,

when updating the application to latest from github an error message is being displayed when running the "makemigrations" command and on application startup.

## Steps to Reproduce

1. upgrade existing application to latest
2. install requirements using pip command
3. run "python manage.py makemigrations"

## Expected Behavior

Command executes successfully.

## Actual Behavior

Error message displayed.

## Screenshots

> File "/opt/horilla/horilla/notifications/migrations/0001_initial.py", line 7, in <module>
>     import jsonfield.fields
>   File "/opt/horilla/horillaenv/lib/python3.10/site-packages/jsonfield/__init__.py", line 3, in <module>
>     from .fields import JSONField
>   File "/opt/horilla/horillaenv/lib/python3.10/site-packages/jsonfield/fields.py", line 9, in <module>
>     from django.utils.translation import ugettext_lazy as _
> ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/opt/horilla/horillaenv/lib/python3.10/site-packages/django/utils/translation/__init__.py)
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
>     return self.cursor.execute(sql, params)
>   File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
>     return super().execute(query, params)
> sqlite3.OperationalError: no such table: employee_bonuspoint

## Environment

- **Django Version:** 4.2.3
- **Python Version:** 3.10.12
- **Operating System:** Ubuntu 22.04.3 LTS

## Additional Information

_[Any other relevant information, logs, error messages, or context that might help in understanding and fixing the issue.]_

## Possible Solution

This issue was already reported (https://github.com/horilla-opensource/horilla/issues/53). A search for the error message provided the following result: https://forum.djangoproject.com/t/importerror-cannot-import-name-ugettext-lazy-from-django-utils-translation/10943
Replacing the package "django-jsonfield" with "django-jsonfield-backport" inside the file "requirements.txt" and installing the packages did not solve the issue.

## Labels

bug

## Priority

medium

## Assignees

_[If you want to suggest an assignee or tag a specific person to look into this issue, mention their GitHub username here.]_

## Related Issues

https://github.com/horilla-opensource/horilla/issues/53

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
This error will only occur on the first makemigration command(the command will be completely executed, even if error is raised). After migrating the database, there won't be any issue.
We will update it with a try exception aftersome, as if it is provided now, there will be migrating issues for existing users.

If you still face issue with the migration command, let us know.

With Regards,
**Team Horilla**

**Comment by sergej-wv** [comment]
Hello,

thank you for the hint. I attempted to upgrade again. The code was pulled from git. The command "python manage.py makemigrations" was executed multiple times resulting in the same error message:

<details>
 Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: payroll_workrecord.last_update

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/horilla/horilla/payroll/models/models.py", line 410, in run
    for work_record in work_records:
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: payroll_workrecord.last_update
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: onboarding_candidatetask.stage_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/horilla/horilla/onboarding/models.py", line 210, in run
    for c_task in cand_task:
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: onboarding_candidatetask.stage_id_id
Traceback (most recent call last):
  File "/opt/horilla/horilla/manage.py", line 22, in <module>
    main()
  File "/opt/horilla/horilla/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/core/management/commands/makemigrations.py", line 137, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 229, in build_graph
    self.load_disk()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 120, in load_disk
    migration_module = import_module(migration_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/horilla/horilla/notifications/migrations/0001_initial.py", line 7, in <module>
    import jsonfield.fields
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/jsonfield/__init__.py", line 3, in <module>
    from .fields import JSONField
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/jsonfield/fields.py", line 9, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/opt/horilla/horillaenv/lib/python3.10/site-packages/django/utils/translation/__init__.py)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: employee_bonuspoint

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/horilla/horilla/employee/models.py", line 625, in run
    if not BonusPoint.objects.filter(employee_id__id = employee.id).exists():
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 598, in has_results
    return compiler.has_results()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: employee_bonuspoint
</details>

The "migrate" command was then executed, resulting in the same error. Starting up the server displayed the same error and the service was unavailable.

Currently the changes were reverted to the last working state. But we would like to ask for assistance on how to overcome this issue.

For further details feel free to ask.

Best regards,
Sergej Kurtin

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
Sorry the inconvenience caused.
We have added a solution for this issue in the commit [[FIX] GENERAL: Migration issue](https://github.com/horilla-opensource/horilla/commit/33622c5f8251be19b846e16fdcb195ca5ce65a0a)

If the issue still persists after, let us know.

With Regards,
**Team Horilla**

**Comment by sergej-wv** [comment]
Hello,

the changes did not solve the issues above. The commands returned again the same error messages. After looking at the se again a change was made to a file inside the python package:
>horillaenv/lib/python3.10/site-packages/jsonfield/fields.py
line 9:
from:  `from django.utils.translation import ugettext_lazy as _`
to:      `from django.utils.translation import gettext_lazy as _`

The error message about missing columns were displayed again when executing "makemigration" but then the command finished successfully.

I also was notified that we pull our code from the fork https://github.com/web-vision/horilla-opensource because it contains translations. The commits are transfered to the fork before the pull to the server. I tested the update using the code from here. After running "makemigrations", which succeeded after complaining about missing columns, and "migrate", the application would not start. The error message would point to missing columns and tables but different compared to the ones mentioned above.

For now I would like to ask to include the module edit mentioned above or to adjust the usage of it inside the code.

Best regards,
Sergej Kurtin

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
Sure. We'll look into it and post an update on it soon.

With Regards,
**Team Horilla**

**Comment by ashwanthbalakrishnan5** [comment]
Still getting issues while clone and setting for first time.
If you could release a stable version and maintain versioning it would be nice

Thanks

**Comment by horilla-opensource** [comment]
Hi @ashwanthbalakrishnan5 ,
Sorry for the inconvenience.
We are working on the release of the first version which is why we couldn't acknowledge all the issues recently.
We'll be releasing our first stable version in the coming days.
We'll let you know once it is released.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @ashwanthbalakrishnan5 ,
We have tested it with a blank database and new venv and it is successfully working on our side.
Can you specify the error that you are facing?

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
Has the issue been resolved?

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
Any updates on the solution?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
Any updates?

With Regards,
**Team Horilla**

**Comment by ashwanthbalakrishnan5** [comment]
Hi @horilla-opensource,
The issue is resolved, you may close this issue.

Thanks

**Comment by horilla-opensource** [comment]
Thanks.
