### ISSUE TITLE
HTTP 500 error when submitting attendance request due to "Object of type time is not JSON serializable"

### ISSUE THREAD

**Issue by sergej-wv** [horilla-opensource/horilla#80]
# Bug Report

## Description

Hello,

when submitting attendance requests, well, nothing happens inside the webUI when pressing the button. The request is answered with a 500 error code.

## Steps to Reproduce

1. visit "attendance/request-attendance-view/" inside application
2. Press "+ New Requests" button
3. fill out fields
4. submit

## Expected Behavior

An attendance request was submitted.

## Actual Behavior

The request is answered with a 500 error code.

## Screenshots

From the 500 response:
<details>
Environment:

Request Method: POST
Request URL: https://[REDACTED]/attendance/request-new-attendance

Django Version: 4.2.7
Python Version: 3.10.12
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'notifications',
 'mathfilters',
 'corsheaders',
 'simple_history',
 'django_filters',
 'base',
 'recruitment',
 'employee',
 'leave',
 'pms',
 'onboarding',
 'asset',
 'attendance',
 'payroll',
 'widget_tweaks',
 'django_apscheduler',
 'horilla_audit',
 'horilla_widgets',
 'horilla_crumbs',
 'horilla_documents',
 'haystack',
 'helpdesk',
 'offboarding']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'base.middleware.CompanyMiddleware',
 'base.thread_local_middleware.ThreadLocalMiddleware']

Traceback (most recent call last):
  File "/opt/horilla/horilla/horilla/decorators.py", line 128, in wrapped_view
    func = view_func(request, *args, **kwargs)
  File "/opt/horilla/horilla/attendance/views/requests.py", line 136, in request_new
    if form.is_valid():
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 434, in full_clean
    self._clean_form()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 455, in _clean_form
    cleaned_data = self.clean()
  File "/opt/horilla/horilla/attendance/forms.py", line 630, in clean
    attendance.requested_data = json.dumps(data)
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

During handling of the above exception (Object of type time is not JSON serializable), another exception occurred:
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/horilla/horilla/horilla/decorators.py", line 133, in wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/horilla/horilla/attendance/views/requests.py", line 136, in request_new
    if form.is_valid():
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 434, in full_clean
    self._clean_form()
  File "/opt/horilla/horillaenv/lib/python3.10/site-packages/django/forms/forms.py", line 455, in _clean_form
    cleaned_data = self.clean()
  File "/opt/horilla/horilla/attendance/forms.py", line 630, in clean
    attendance.requested_data = json.dumps(data)
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

Exception Type: TypeError at /attendance/request-new-attendance
Exception Value: Object of type time is not JSON serializable

</details>

## Environment

- **Django Version:** 4.2.7
- **Python Version:** Python 3.10.12
- **Operating System:** Ubuntu 22.04.3 LTS
- **Browser:** Firefox 121.0.1

## Labels

bug

## Priority

medium

## Assignees

_[If you want to suggest an assignee or tag a specific person to look into this issue, mention their GitHub username here.]_

## Related Issues

_[If there are any related issues or pull requests, mention them here. This is optional.]_

**Note:** _Remember to search through existing issues before submitting a new one to ensure that the issue hasn't been reported already. Provide as much information as possible to help the maintainers understand and address the problem effectively._

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
We have added the solution for it in the latest code.
Please check and let us know if you face any more issues in this area.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
Were you able to test out the solution?
If its fixed, can we please close the issue?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
Any updates?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @sergej-wv ,
We are closing this issue due to inactivity. It seems that there hasn't been any recent activity or discussion, and we believe it may have been resolved or is no longer relevant. 
If you feel this issue is still important and should be addressed, please feel free to reopen it or create a new issue with updated details. 

With Regards,
**Team Horilla**
